import {
  house1,
  house2,
  house3,
  house4,
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  villa1,
  villa2,
  house5,
  house6,
  villa3,
  apartment1,
  apartment2,
  apartment3,
  apartment4,
  apartment5,
  avatar5,
  avatar6,
  avatar7,
  avatar8,
  avatar9,
  avatar10,
  avatar11,
  avatar12,
  avatar13,
  avatar14,
} from "../images";

const adCardsArr = [
  {
    filterType: "House",
    image: house1,
    labelType: "popular",
    title: "Roselands House",
    price: "$ 35.000.000",
    sellerAvatar: avatar1,
    sellerName: "Dianne Russell",
    sellerLocation: "Manchester, Kentucky",
  },
  {
    filterType: "House",
    image: house2,
    labelType: "new-house",
    title: "Woodlandside",
    price: "$ 20.000.000",
    sellerAvatar: avatar2,
    sellerName: "Robert Fox",
    sellerLocation: "Dr. San Jose, South Dakota",
  },
  {
    filterType: "House",
    image: house3,
    labelType: "best-deals",
    title: "Old Lighthouse",
    price: "$ 44.000.000",
    sellerAvatar: avatar3,
    sellerName: "Ronald Richards",
    sellerLocation: "Santa Ana, Illinois",
  },
  {
    filterType: "House",
    image: house4,
    labelType: "popular",
    title: "Cosmo's House",
    price: "$ 22.000.000",
    sellerAvatar: avatar4,
    sellerName: "Jenny Wilson",
    sellerLocation: "Preston Rd. Inglewood, Maine 98380",
  },
  {
    filterType: "House",
    image: house5,
    labelType: "best-deals",
    title: "Rustic Farmhouse",
    price: "$ 15.000.000",
    sellerAvatar: avatar8,
    sellerName: "Sarah Adams",
    sellerLocation: "Hallock, North Dakota",
  },
  {
    filterType: "House",
    image: house6,
    labelType: "best-deals",
    title: "Cozy Cottage",
    price: "$ 20.000.000",
    sellerAvatar: avatar5,
    sellerName: "Emily Thompson",
    sellerLocation: "Springfield, Oregon",
  },
  {
    filterType: "Villa",
    image: villa1,
    labelType: "popular",
    title: "Beachfront Villa",
    price: "$ 77.000.000",
    sellerAvatar: avatar6,
    sellerName: "Javier Rodriguez",
    sellerLocation: "Miami, Florida",
  },
  {
    filterType: "Villa",
    image: villa2,
    labelType: "popular",
    title: "Mountain Retreat",
    price: "$ 99.999.999",
    sellerAvatar: avatar9,
    sellerName: "Emma Wilson",
    sellerLocation: "Aspen, Colorado",
  },
  {
    filterType: "Villa",
    image: villa3,
    labelType: "new-house",
    title: "Modern Mansion",
    price: "$ 57.000.000",
    sellerAvatar: avatar7,
    sellerName: "Michael Johnson",
    sellerLocation: "Beverly Hills, California",
  },
  {
    filterType: "Apartment",
    image: apartment5,
    labelType: "new-house",
    title: "Modern City Apartment",
    price: "$ 33.000.000",
    sellerAvatar: avatar12,
    sellerName: "Benjamin Anderson",
    sellerLocation: "Chicago, Illinois",
  },
  {
    filterType: "Apartment",
    image: apartment2,
    labelType: "popular",
    title: "Historic Brownstone Apartment",
    price: "$ 22.000.000",
    sellerAvatar: avatar10,
    sellerName: "Emily Johnson",
    sellerLocation: "Boston, Massachusetts",
  },
  {
    filterType: "Apartment",
    image: apartment1,
    labelType: "popular",
    title: "Downtown Loft Apartment",
    price: "$ 54.000.000",
    sellerAvatar: avatar11,
    sellerName: "Jessica Thompson",
    sellerLocation: "New York City, New York",
  },
  {
    filterType: "Apartment",
    image: apartment3,
    labelType: "best-deals",
    title: "Luxury Condo with a View",
    price: "$ 34.000.000",
    sellerAvatar: avatar14,
    sellerName: "Michael Davis",
    sellerLocation: "Los Angeles, California",
  },
  {
    filterType: "Apartment",
    image: apartment4,
    labelType: "best-deals",
    title: "Slum apartament",
    price: "$ 9.999.999",
    sellerAvatar: avatar13,
    sellerName: "Larry Johnson",
    sellerLocation: "New York, Brooklyn",
  },
];

export default adCardsArr;
